---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  namespace: privatecloud
#  app: frontent
spec:
  selector:
    matchLabels:
      app: argocd-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: gcr.io/genial-reporter-329010/argocd:v1
        ports:
          - containerPort: 5000
      
