---
apiVersion: v1
kind: Service
metadata:
  name: argoservice
#  app: service
spec:
  type: LoadBalancer
  selector:
    app: argocd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
